const QUESTIONS = window.QUESTIONS || [];
const TYPE_NAMES = {tf:'OX', choice:'객관식', blank:'빈칸', codeOutput:'실행 결과', codeFill:'코드 빈칸', codeTask:'코드 작성'};
const KEY='javascript_practice_lab_full_v3';
let saved = JSON.parse(localStorage.getItem(KEY) || '{"answers":{}}');
let current=null, selected=null, currentPool=[];
const $=id=>document.getElementById(id);
const cats=['ALL', ...new Set(QUESTIONS.map(q=>q.cat))];
$('catSel').innerHTML=cats.map(c=>`<option value="${c}">${c==='ALL'?'모든 영역':c}</option>`).join('');
$('totalCount').textContent=QUESTIONS.length;
function save(){ localStorage.setItem(KEY, JSON.stringify(saved)); refreshStats(); }
function norm(v){ return String(v ?? '').trim().replace(/\r/g,'').replace(/[ \t]+/g,' '); }
function filtered(){ const c=$('catSel').value, t=$('typeSel').value; return QUESTIONS.filter(q=>(c==='ALL'||q.cat===c)&&(t==='ALL'||q.type===t)); }
function refreshPool(){ currentPool=filtered(); $('poolInfo').textContent=`현재 ${currentPool.length}문항`; renderProgress(); }
function pickRandom(pool=currentPool){ if(!pool.length) return; let q=pool[Math.floor(Math.random()*pool.length)]; if(current && pool.length>1) while(q.id===current.id) q=pool[Math.floor(Math.random()*pool.length)]; renderQuestion(q); }
function renderQuestion(q){ current=q; selected=null; $('catTag').textContent=q.cat; $('topicTag').textContent=q.topic; $('typeTag').textContent=TYPE_NAMES[q.type]; $('qtitle').textContent=q.q; $('feedback').className='feedback'; $('feedback').textContent=''; $('console').style.display='none'; $('runBtn').style.display=['codeOutput','codeTask'].includes(q.type)?'inline-block':'none'; let s=''; if(q.code) s += `<pre class="code">${escapeHtml(q.code)}</pre>`; if(q.type==='tf'){ s += `<div class="options"><button class="opt" data-v="true">O · 맞다</button><button class="opt" data-v="false">X · 아니다</button></div>`; } else if(q.type==='choice'){ s += `<div class="options">${q.choices.map((x,i)=>`<button class="opt" data-v="${i}">${String.fromCharCode(65+i)}. ${escapeHtml(x)}</button>`).join('')}</div>`; } else if(q.type==='codeTask'){ s += `<textarea class="editor" id="answerEditor">${escapeHtml(q.starter||'')}</textarea>`; } else { s += `<div class="answerRow"><input id="answerInput" placeholder="${q.type==='codeFill'?'빈칸에 들어갈 코드를 입력':'정답을 입력'}"></div>`; } $('qbody').innerHTML=s; document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{ document.querySelectorAll('.opt').forEach(x=>x.classList.remove('sel')); b.classList.add('sel'); selected=b.dataset.v; }); }
function escapeHtml(s){ return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function userAnswer(){ if(current.type==='tf') return selected===null?null:(selected==='true'); if(current.type==='choice') return selected===null?null:Number(selected); if(current.type==='codeTask') return $('answerEditor').value; return $('answerInput')?.value ?? ''; }
function check(){ if(!current) return; const a=userAnswer(); let ok=false; if(current.type==='tf'||current.type==='choice') ok=(a===current.answer); else if(current.type==='codeTask'){ runTask(true); return; } else if(current.type==='codeOutput') ok=norm(a)===norm(current.answer); else ok=norm(a).replace(/\s/g,'')===norm(current.answer).replace(/\s/g,''); record(ok,a); showFeedback(ok); }
function record(ok,a){ const prev=saved.answers[current.id]||{tries:0}; saved.answers[current.id]={tries:(prev.tries||0)+1, correct:ok, last:a}; save(); }
function showFeedback(ok, extra=''){ $('feedback').className='feedback '+(ok?'ok':'bad'); $('feedback').innerHTML=`<b>${ok?'정답입니다 ✓':'다시 생각해보세요 ✕'}</b><br>${escapeHtml(current.ex||'')}${extra?'<br>'+escapeHtml(extra):''}`; }
function workerRun(code, testExpr=null, cb){ const workerSrc = `const logs=[]; const fmt=(v)=>{ if(typeof v==='string') return v; try{ return JSON.stringify(v); }catch(e){ return String(v); } }; console.log=(...a)=>logs.push(a.map(fmt).join(' ')); self.onmessage = async e => { try { let result; if(e.data.test) { result = (0,eval)(e.data.code + "\\n;(" + e.data.test + ")"); } else { result = (0,eval)(e.data.code); } if(result && typeof result.then==='function') result=await result; postMessage({ok:true, logs, result: !!result}); } catch(err) { postMessage({ok:false, logs, error:String(err && err.stack || err)}); } };`; const blob=new Blob([workerSrc],{type:'application/javascript'}); const w=new Worker(URL.createObjectURL(blob)); const timer=setTimeout(()=>{w.terminate(); cb({ok:false,error:'실행 시간이 너무 길어 중단했습니다.'})},1800); w.onmessage=e=>{clearTimeout(timer);w.terminate();cb(e.data)}; w.onerror=e=>{ clearTimeout(timer); const msg = e && e.message ? e.message : 'Worker 실행 오류'; w.terminate(); cb({ok:false,error:msg}); }; w.postMessage({code,test:testExpr}); }
function runCurrent(){ if(!current) return; if(current.type==='codeOutput'){ $('console').style.display='block'; $('console').textContent='실행 중...'; workerRun(current.code,null,r=>{$('console').textContent=r.ok?(r.logs.join('\n')||'(출력 없음)'):(r.error||'오류')}); } else if(current.type==='codeTask') runTask(false); }
function runTask(isCheck){ const code=$('answerEditor').value; $('console').style.display='block'; $('console').textContent='테스트 실행 중...'; workerRun(code,current.test,r=>{ if(!r.ok){ $('console').textContent=(r.logs||[]).join('\n')+'\n'+(r.error||'실행 오류'); if(isCheck){record(false,code);showFeedback(false,'실행 오류가 있습니다.')} return; } $('console').textContent=(r.logs||[]).join('\n') + (r.result?'\n✓ 테스트 통과':'\n✕ 테스트 실패'); if(isCheck){record(!!r.result,code);showFeedback(!!r.result, r.result?'제공된 테스트를 통과했습니다.':'제공된 테스트 중 통과하지 못한 경우가 있습니다.');} }); }
function refreshStats(){ const vals=Object.values(saved.answers||{}); const done=vals.length, correct=vals.filter(v=>v.correct).length; $('doneCount').textContent=done; $('accuracy').textContent=done?Math.round(correct/done*100)+'%':'0%'; renderProgress(); renderMastery(); }
function renderProgress(){ const p=currentPool.length?currentPool:filtered(); const done=p.filter(q=>saved.answers[q.id]).length; $('progressBar').style.width=(p.length?done/p.length*100:0)+'%'; $('progressText').textContent=`${done} / ${p.length} 문항 풀이`; }
function renderMastery(){ const cc=[...new Set(QUESTIONS.map(q=>q.cat))]; $('mastery').innerHTML=cc.map(c=>{ const q=QUESTIONS.filter(x=>x.cat===c), a=q.filter(x=>saved.answers[x.id]); const ok=a.filter(x=>saved.answers[x.id].correct).length; const pct=a.length?Math.round(ok/a.length*100):0; return `<div class="mrow"><span>${c}</span><b>${pct}%</b></div>`; }).join(''); }
$('checkBtn').onclick=check; $('runBtn').onclick=runCurrent; $('nextBtn').onclick=()=>pickRandom(); $('randomBtn').onclick=()=>pickRandom(); $('catSel').onchange=()=>{refreshPool();pickRandom();}; $('typeSel').onchange=()=>{refreshPool();pickRandom();}; $('weakBtn').onclick=()=>{ const bad=filtered().filter(q=>saved.answers[q.id] && !saved.answers[q.id].correct); if(!bad.length) alert('현재 필터에서 오답 문항이 없습니다.'); else pickRandom(bad); }; $('resetBtn').onclick=()=>{ if(confirm('모든 풀이 기록을 초기화할까요?')){ saved={answers:{}}; save(); pickRandom(); } }; $('playRun').onclick=()=>{ $('playConsole').textContent='실행 중...'; workerRun($('playCode').value,null,r=>{$('playConsole').textContent=r.ok?(r.logs.join('\n')||'(출력 없음)'):(r.error||'오류')}); };
refreshPool(); refreshStats(); pickRandom();
const REPO_BASE = 'https://kbj0072.github.io/yc_react/';
const CAT_CHAPTERS = {'1. truthy & falsy': {path:'s02/ch01.html', title:'2-1. truthy & falsy'},'2. 단락 평가': {path:'s02/ch02.html', title:'2-2. 단락 평가'},'3. 객체 자료형과 참조': {path:'s02/ch05.html', title:'2-5. 원시 타입과 객체 타입 차이'},'4. 반복문 응용': {path:'s02/ch06.html', title:'2-6. 반복문 응용하기'},'5. 구조 분해 할당': {path:'s02/ch03.html', title:'2-3. 구조 분해 할당'},'6. 스프레드 연산자와 rest': {path:'s02/ch04.html', title:'2-4. 스프레드 연산자와 rest 매개변수'},'7. 배열과 메서드': {path:'s02/ch07.html', title:'2-7~2-9. 배열과 메서드'},'8. Date 객체와 날짜': {path:'s02/ch10.html', title:'2-10. Date 객체와 날짜'},'9. 비동기 처리': {path:'s02/ch11.html', title:'2-11~2-14. 비동기 처리'}};
function switchView(id){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active', v.id===id)); document.querySelectorAll('.tabbtn').forEach(b=>b.classList.toggle('active', b.dataset.view===id)); window.scrollTo({top:0,behavior:'smooth'}); }
document.querySelectorAll('.tabbtn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function openRepoChapter(path,title){ const url=REPO_BASE+path; const frame=document.getElementById('repoFrame'); frame.src=url; document.getElementById('repoNow').textContent=title; document.getElementById('repoOpen').href=url; document.querySelectorAll('.chapterBtn').forEach(b=>b.classList.toggle('active', b.dataset.path===path)); switchView('repoView'); }
document.querySelectorAll('.chapterBtn').forEach(b=>b.addEventListener('click',()=>openRepoChapter(b.dataset.path,b.dataset.title)));
const originalRenderQuestion = renderQuestion;
renderQuestion = function(q){ originalRenderQuestion(q); const info=CAT_CHAPTERS[q.cat]; const txt=document.getElementById('relatedText'); const btn=document.getElementById('relatedBtn'); if(info){ txt.textContent=info.title+' 예제를 직접 수정하고 실행해볼 수 있습니다.'; btn.style.display='inline-block'; } else { txt.textContent='연결된 교재 예제가 없습니다.'; btn.style.display='none'; } };
if(current) renderQuestion(current);
const ARRAY_SUBMAP = {a1:'s02/ch07.html',a2:'s02/ch07.html',a3:'s02/ch07.html',a4:'s02/ch07.html',a5:'s02/ch07.html',a6:'s02/ch07.html',a7:'s02/ch07.html',a8:'s02/ch07.html',a9:'s02/ch07.html',a10:'s02/ch07.html',a11:'s02/ch07.html',a12:'s02/ch07.html',a13:'s02/ch08.html',a14:'s02/ch08.html',a15:'s02/ch08.html',a16:'s02/ch08.html',a17:'s02/ch08.html',a18:'s02/ch08.html',a19:'s02/ch08.html',a20:'s02/ch09.html',a21:'s02/ch09.html',a22:'s02/ch09.html',a23:'s02/ch09.html',a24:'s02/ch09.html',a25:'s02/ch09.html',a26:'s02/ch09.html',a27:'s02/ch09.html',a28:'s02/ch09.html',a29:'s02/ch09.html',a30:'s02/ch09.html',a31:'s02/ch09.html',a32:'s02/ch09.html'};
document.getElementById('relatedBtn').onclick=()=>{ if(!current) return; if(current.cat==='7. 배열과 메서드' && ARRAY_SUBMAP[current.id]){ const p=ARRAY_SUBMAP[current.id]; const ttl = p.includes('ch07')?'2-7. 배열과 메서드 (1) - 요소 조작':p.includes('ch08')?'2-8. 배열과 메서드 (2) - 순회와 탐색':'2-9. 배열과 메서드 (3) - 변형 메서드'; openRepoChapter(p,ttl); return; } if(current.cat==='9. 비동기 처리'){ let p='s02/ch11.html',ttl='2-11. 동기와 비동기'; if(['as4','as5','as6'].includes(current.id)){p='s02/ch12.html';ttl='2-12. 비동기 작업 처리하기 1 - 콜백함수';} if(['as7','as8','as9','as10','as11','as12','as13','as14','as15','as16'].includes(current.id)){p='s02/ch13.html';ttl='2-13. 비동기 작업 처리하기 2 - Promise';} openRepoChapter(p,ttl); return; } const info=CAT_CHAPTERS[current.cat]; if(info) openRepoChapter(info.path,info.title); };